spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=82
management.endpoints.web.exposure.include=*
management.endpoint.mappings.enabled=true

# Optional logging/debug
logging.level.org.hibernate.SQL=DEBUG

# Replace with your actual node and explorer URLs
ergopay.nodeApiUrl=http://localhost:9053/
ergopay.explorerApiUrl=http://localhost:8080/api/


embedded.postgres.data-directory=./data/postgres/db
embedded.postgres.credentials-file=./data/postgres/credentials.properties
embedded.postgres.username=ergopay
embedded.postgres.default-password=ergopay
embedded.postgres.database=ergopay
