#!/usr/bin/env bash
set -euo pipefail

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "This script must be run as root (try prefixing with sudo)." >&2
  exit 1
fi

if ! command -v nginx >/dev/null 2>&1; then
  echo "nginx is not installed. Install it and try again." >&2
  exit 1
fi

SERVER_NAME=""
PORT=82
ENABLE_HTTPS=false
FORCE=false

usage() {
  cat <<USAGE
Usage: $0 --server-name example.com [--port 82] [--https] [--force]

Options:
  --server-name   Fully qualified domain name for the portal (required).
  --port          Internal port where the Spring Boot app listens (default: 82).
  --https         Emit an additional HTTPS server block (requires certificates configured separately).
  --force         Overwrite any existing configuration file.
  --help          Show this message.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --server-name)
      SERVER_NAME="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --https)
      ENABLE_HTTPS=true
      shift 1
      ;;
    --force)
      FORCE=true
      shift 1
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$SERVER_NAME" ]]; then
  echo "--server-name is required." >&2
  usage >&2
  exit 1
fi

CONFIG_NAME="ergopay-portal.conf"
AVAILABLE_DIR="/etc/nginx/sites-available"
ENABLED_DIR="/etc/nginx/sites-enabled"
CONFIG_PATH="${AVAILABLE_DIR}/${CONFIG_NAME}"
TMP_CONF="$(mktemp)"
trap 'rm -f "$TMP_CONF"' EXIT

cat <<CONF >"$TMP_CONF"
# Generated by configure_nginx.sh for ErgoPay Payment Portal
server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAME};

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
    }
}
CONF

if $ENABLE_HTTPS; then
  cat <<'CONF' >>"$TMP_CONF"

# HTTPS reverse proxy block (requires valid TLS certs at /etc/letsencrypt/live/<domain>/)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name SERVER_NAME_PLACEHOLDER;

    ssl_certificate /etc/letsencrypt/live/SERVER_NAME_PLACEHOLDER/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/SERVER_NAME_PLACEHOLDER/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:PORT_PLACEHOLDER;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
    }
}
CONF
  sed -i "s/SERVER_NAME_PLACEHOLDER/${SERVER_NAME}/g" "$TMP_CONF"
  sed -i "s/PORT_PLACEHOLDER/${PORT}/g" "$TMP_CONF"
fi

if [[ -f "$CONFIG_PATH" && $FORCE == false ]]; then
  echo "${CONFIG_PATH} already exists. Use --force to overwrite it." >&2
  exit 1
fi

install -d -m 755 "$AVAILABLE_DIR" "$ENABLED_DIR"
install -m 644 "$TMP_CONF" "$CONFIG_PATH"
ln -sf "$CONFIG_PATH" "${ENABLED_DIR}/${CONFIG_NAME}"

nginx -t
systemctl reload nginx

echo "Nginx configuration installed for ${SERVER_NAME} (proxying to 127.0.0.1:${PORT})."
